name = "Obsidian"
uuid = "0a1fef19-5aa4-4284-b8c1-c1397acb49d1"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
TestSetExtensions = "2"
julia = "1"