name = "Obsidian"
uuid = "0a1fef19-5aa4-4284-b8c1-c1397acb49d1"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.4.7"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
DocStringExtensions = "0.9"
Documenter = "0.27, 1"
TestSetExtensions = "2"
YAML = "0.4"
julia = "1"
