project:
  type: website
jupyter: julia-1.10  
theme: spacelab
execute:
  freeze: auto
date: last-modified  
margin-header: "Documentation for unpublished version in development: `0.3.0`"
format:
  html: 
    toc: true


website:
  title: "obsidian"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Concepts"
        file: concepts/index.qmd           
      - text: "Tutorials"
        file: tutorials/index.qmd          
      - text: "Guides"
        file: guides/index.qmd           
      - text: "Reference"
        file: reference/index.qmd  
    right:   
      - icon: github
        href: https://github.com/neelsmith/Obsidian.jl
        aria-label: GitHub

  sidebar:
    - title: "Tutorials"
      contents: 
        - tutorials/index.qmd
        - tutorials/vault_tutorial.qmd
        - tutorials/properties_tutorial.qmd

    - title: "Guides"
      contents:
        - guides/index.qmd
        - guides/markdownoptions.qmd
        - guides/website.qmd

    - title: "Reference"
      contents: 
        - reference/index.qmd
        - reference/apis.qmd

    - title: "Concepts"
      contents: 
        - concepts/index.qmd

        

    - title: "Home"
      contents:
        - index.qmd               
 

